### ISSUE TITLE
Improve Data Generation for MoBIE

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie#17]
@martinschorb @constantinpape 

Issue to collect ideas how to make generating data for MoBIE more convenient.

- Somehow using functionality from BigStitcher could be useful (the have a nice way to define datasets and even code to save everything as h5/xml)

**Comment by tischi** [comment]
@martinschorb 
The logic of BigStitcher with one big xml for many sources could also be used for cases like the tomograms that should be displayed together in a random grid.
I wonder whether it would work straight away when we would put such an xml into MoBIE.

**Comment by martinschorb** [comment]
I tried some hardcore challenge for MoBIE-beta:

see `/g/cba/exchange/Martin_BDV/montages/mobie`

the error message looks like it is a general problem with the loader and not with that particular data structure...

```
Adding source: test...
[ERROR] Module threw exception
java.lang.ClassCastException: spim.fiji.spimdata.imgloaders.StackImgLoaderIJ cannot be cast to bdv.ViewerImgLoader
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:259)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:293)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:92)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:581)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:364)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:339)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:296)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:53)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:35)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:99)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:62)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
We can create projects from the fiji plugin now and the python library is also documented better and easier to install.
